apiVersion: apps/v1
kind: Deployment
metadata:
  name: salle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salle-service
  template:
    metadata:
      labels:
        app: salle-service
    spec:
      containers:
        - name: salle
          image: wassimabderrazak/salle-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: JWT_SECRET
              value: devopssecretkey
            - name: PG_USER
              value: devops
            - name: PG_PASSWORD
              value: devops
            - name: PG_DB
              value: salle_db
            - name: PG_HOST
              value: postgres-service
            - name: PG_PORT
              value: "5433"
