name: Full CI/CD Pipeline for DevOps Project

on:
  push:
    branches: [main]

jobs:
  build-deploy-user-service:
    name: Build & Deploy user-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & run tests
        run: |
          cd user-service
          npm install
          npm test || echo "tests non implémentés"

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./user-service
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm Deploy
        run: helm upgrade --install user-service ./helm/user-service --namespace default

  build-deploy-salle-service:
    name: Build & Deploy salle-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & run tests
        run: |
          cd salle-service
          npm install
          npm test || echo "tests non implémentés"

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/salle-service:latest ./salle-service
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/salle-service:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm Deploy
        run: helm upgrade --install salle-service ./helm/salle-service --namespace default

  build-deploy-reservation-service:
    name: Build & Deploy reservation-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & run tests
        run: |
          cd reservation-service
          npm install
          npm test || echo "tests non implémentés"

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reservation-service:latest ./reservation-service
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/reservation-service:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm Deploy
        run: helm upgrade --install reservation-service ./helm/reservation-service --namespace default